modelClass: CustomChat\ChatPlugin\Models\Message


list:
    columns:
        message:
            label: Message
            searchable: true
            type: text
        user:
            label: User
            relation: user
            select: concat(first_name, ' ', last_name)
        chat:
            label: Chat
            relation: chat
            select: name
        created_at:
            label: Created At
            type: datetime