modelClass: CustomChat\ChatPlugin\Models\Message

form:
    fields:
        message:
            label: Message
            type: textarea
        file:
            label: Upload File
            type: fileupload
            mode: file
        parent_message_id:
            label: Reply To
            type: relation
            nameFrom: message
        reactions:
            label: Reactions
            type: repeater
            prompt: Add Reaction
            form:
                fields:
                    emoji:
                        label: Emoji
                        type: text
                        span: auto