modelClass: CustomChat\ChatPlugin\Models\Chat

form:
    fields:
        name:
            label: Chat Name
            type: text
            span: left
        user1_id:
            label: User 1
            type: relation
            span: right
            nameFrom: concat(first_name, ' ', last_name)
        user2_id:
            label: User 2
            type: relation
            span: right
            nameFrom: concat(first_name, ' ', last_name)