modelClass: CustomChat\ChatPlugin\Models\Chat

list:
    columns:
        name:
            label: Chat Name
            searchable: true
        user1:
            label: User 1
            relation: user1
            select: concat(first_name, ' ', last_name)
        user2:
            label: User 2
            relation: user2
            select: concat(first_name, ' ', last_name)
        created_at:
            label: Created At
            type: datetime